"""ASE-v0 request-local representation and mechanical control continuity.

No task semantics, requirement extraction, or additional model stage live here.
"""

from __future__ import annotations

import hashlib
import json

from .dcm_v0 import DecisionMeasurementBoundary


REFERENCE_LIMIT = 3600
CONTINUITY_LIMIT = 1000
ANCHOR_LIMIT = 260
FOLLOW_LIMIT = 160
RATIONALE_LIMIT = 180

SYSTEM_PROMPT = """You are the persistent Supervisor for the full public task. The public task is authoritative. At initialization, read task/original_task.txt and inspect the pristine task/workspace/ with the ordinary tools, investigate as needed, then write a short natural-language monitor/reference.md: required behavior and constraints that may change later control, important integration consequences, distinctions that could give false positive evidence, and observations that may distinguish consequential states. This is your revisable interpretation, not verified truth. Do not use reference.md as a progress or completion ledger: do not put Target X complete, 5/7 done, current repair status, or local resolution there. Revise it with the existing private file tools when your understanding changes; no headings, form, or per-review rewrite are required.

Task tests, build results, and Agent claims are evidence only for what they actually show. Use current public feedback to decide whether to observe, send a useful correction for a material discrepancy, follow its recovery, or let work proceed. If an observation cannot distinguish states that would change control, you may change the measurement. After intervening, inspect the Task's actual understanding, action, and result; revise your advice when feedback undermines it. Release local supervision when its grounds are adequate without investigating every unknown. At completion, judge the whole public mission, not merely recent repairs. Use the seven ordinary tools directly; no fixed reasoning fields or output sections are required.

monitor/working.md remains private scratch and continuation state, not the automatically supplied task reference. Reference, prior local control, and recent public events are navigational inputs, never substitutes for original evidence. Task evidence is read-only under task/; private files are writable under monitor/. code_run starts in monitor/ and is not a filesystem sandbox."""

RELEASE_GUIDANCE = (
    'This proposed release has not executed. Your current task reference, recent situation and prior '
    'local control context remain available. Reconsider freely: use ordinary tools, change the control '
    'action, or repeat the same kind of release in a new model turn if it remains appropriate.'
)


def digest(value):
    return hashlib.sha256(str(value).encode('utf-8')).hexdigest()


def excerpt(value, limit):
    value = str(value or '').strip()
    return value[:limit] + (' [excerpt truncated]' if len(value) > limit else '')


def reference_surface(workspace, limit=REFERENCE_LIMIT):
    """Bounded head+tail transport of model-owned bytes, never a semantic summary."""
    if type(limit) is not int or limit < 512:
        raise ValueError('ASE reference limit must be an integer >= 512')
    try:
        source = workspace.resolve_read('monitor/reference.md').read_bytes()
        content = source.decode('utf-8', errors='replace')
        status = 'present' if content.strip() else 'empty'
    except FileNotFoundError:
        source, content, status = b'', '', 'absent'
    except (OSError, ValueError) as exc:
        source, content, status = b'', '', 'unavailable:' + type(exc).__name__
    header = ('Supervisor Reference — your own revisable interpretation, not verified truth or progress. '
              'The full public task at task/original_task.txt remains authoritative.\n')
    footer = ('\nFull reference: monitor/reference.md; use file_read for any omitted passage.')
    if status != 'present':
        body = f'[Reference {status}; no task interpretation was generated by the runtime.]'
        truncated, visible = False, ''
    else:
        allowance = limit - len(header) - len(footer)
        if len(content) <= allowance:
            body, visible, truncated = content, content, False
        else:
            # The marker's digit count depends on the amount omitted. Iterate
            # mechanically until its length and the two excerpts agree.
            marker = '\n[Middle omitted; read monitor/reference.md for the complete text.]\n'
            for _ in range(4):
                kept = allowance - len(marker)
                head = (kept + 1) // 2
                tail = kept // 2
                omitted = len(content) - kept
                marker = f'\n[Middle omitted: {omitted} characters; read monitor/reference.md.]\n'
            kept = allowance - len(marker)
            head, tail = (kept + 1) // 2, kept // 2
            visible = content[:head] + content[-tail:] if tail else content[:head]
            body, truncated = content[:head] + marker + (content[-tail:] if tail else ''), True
    rendered = header + body + footer
    if len(rendered) > limit:
        raise ValueError('ASE reference surface exceeded its bound')
    return rendered, {
        'path': 'monitor/reference.md', 'status': status,
        'limit_characters': limit, 'source_characters': len(content),
        'visible_characters': len(visible), 'truncated': truncated,
        'source_sha256': hashlib.sha256(source).hexdigest(),
        'rendered_characters': len(rendered),
        'rendered_utf8_bytes': len(rendered.encode('utf-8')),
    }


class LocalContinuity:
    """One local episode: last submitted intervention plus latest follow expectation."""

    def __init__(self, audit):
        self.audit = audit
        self.anchor = None
        self.follow = None
        self.review_id = None
        self.last_output = None
        self.last_call = None
        self.pending_surface = None
        self.follow_count = 0
        self.episode_start_turn = None

    def begin_review(self, review_id):
        self.review_id = review_id
        self.last_output = None
        self.last_call = None
        self.pending_surface = None

    def observe(self, record, line):
        if record.get('review_id') != self.review_id:
            return
        locator = f'monitor/audit/dialogue.jsonl#{line}'
        if record.get('event') == 'model_output' and str(record.get('content') or '').strip():
            self.last_output = {'text': record['content'], 'locator': locator,
                                'model_turn': record.get('turn')}
        elif record.get('event') == 'tool_call':
            try:
                args = json.loads(record.get('arguments') or '{}')
            except (TypeError, ValueError):
                args = {}
            self.last_call = {'name': record.get('name'), 'args': args,
                              'locator': locator, 'model_turn': record.get('turn')}

    def submitted_intervention(self, message, task_turn=None):
        call, rationale = self.last_call or {}, self.last_output or {}
        self.anchor = {'message': excerpt(message, ANCHOR_LIMIT), 'message_sha256': digest(message),
                       'rationale': excerpt(rationale.get('text'), RATIONALE_LIMIT),
                       'rationale_locator': rationale.get('locator'),
                       'action_locator': call.get('locator'), 'review_id': self.review_id}
        self.follow = None
        self.follow_count = 0
        self.episode_start_turn = task_turn
        self.audit('ase_continuity_updated', source='intervene', anchor=self.anchor,
                   task_turn=task_turn, follow_count=0)

    def completed_wait(self, action, task_turn=None):
        if action.kind != 'wait':
            return
        call, rationale = self.last_call or {}, self.last_output or {}
        mode = action.payload.get('mode')
        if mode == 'patrol':
            prior = self.anchor is not None or self.follow is not None
            self.anchor = self.follow = None
            self.follow_count = 0
            self.episode_start_turn = None
            self.audit('ase_continuity_cleared', source='wait_patrol', had_active=prior,
                       action_locator=call.get('locator'), task_turn=task_turn)
        elif mode == 'follow':
            if self.episode_start_turn is None:
                self.episode_start_turn = task_turn
            reason = call.get('args', {}).get('reason') if call.get('name') == 'wait' else None
            self.follow = {'reason': excerpt(reason, FOLLOW_LIMIT),
                           'reason_sha256': digest(reason),
                           'rationale': excerpt(rationale.get('text'), RATIONALE_LIMIT),
                           'action_locator': call.get('locator'), 'review_id': self.review_id}
            self.follow_count += 1
            age = (task_turn - self.episode_start_turn
                   if isinstance(task_turn, int) and isinstance(self.episode_start_turn, int) else None)
            self.audit('ase_continuity_updated', source='wait_follow', follow=self.follow,
                       anchor_locator=self.anchor.get('action_locator') if self.anchor else None,
                       follow_count=self.follow_count, task_turn=task_turn,
                       episode_task_turn_age=age,
                       requested_after_turns=action.payload.get('after_turns'))

    def render(self):
        if self.anchor is None and self.follow is None:
            self.pending_surface = None
            return None
        lines = ['Local Control Continuity — your prior action, not task truth.']
        if self.anchor is not None:
            lines.append('Previous intervention: ' + self.anchor['message'])
            if self.anchor['rationale']:
                lines.append('Prior rationale: ' + self.anchor['rationale'])
            lines.append('Source: ' + str(self.anchor['action_locator'] or 'unavailable'))
        if self.follow is not None:
            if self.follow['reason']:
                lines.append('Currently awaiting: ' + self.follow['reason'])
            elif self.follow['rationale'] and self.anchor is None:
                lines.append('Follow context: ' + self.follow['rationale'])
            lines.append('Follow source: ' + str(self.follow['action_locator'] or 'unavailable'))
        lines.append('Current public feedback may confirm, revise, or invalidate this local concern.')
        content = '\n'.join(lines)
        if len(content) > CONTINUITY_LIMIT:
            raise ValueError('ASE continuity surface exceeded its bound')
        self.pending_surface = {'content': content, 'sha256': digest(content),
                                'anchor_locator': self.anchor.get('action_locator') if self.anchor else None,
                                'follow_locator': self.follow.get('action_locator') if self.follow else None}
        return content

    def surface_visible(self):
        shown, self.pending_surface = self.pending_surface, None
        if shown is not None:
            self.audit('ase_continuity_surface_injected', **shown,
                       rendered_characters=len(shown['content']))
        return shown


class ReconsiderationBoundary(DecisionMeasurementBoundary):
    """The existing DCM mechanical two-turn boundary with shorter ASE wording."""

    def __init__(self, audit, visible_context):
        super().__init__(audit)
        self.visible_context = visible_context

    def release(self, kind, frame, arguments):
        prior = self.challenge
        self.audit('ase_release_attempted', release_kind=kind, frame=frame,
                   proposed_args=dict(arguments), visible_context=self.visible_context())
        result = super().release(kind, frame, arguments)
        if result is not None and self.challenge is not None and self.challenge is not prior:
            result = {'status': 'release_not_executed',
                      'challenge_id': self.challenge['challenge_id'],
                      'proposed_action': 'wait(mode=patrol)' if kind == 'patrol'
                                         else 'allow_complete(result=resolve)',
                      'proposed_reason': arguments.get('reason'), 'message': RELEASE_GUIDANCE}
            self.audit('ase_reconsideration_boundary', challenge_id=self.challenge['challenge_id'],
                       release_kind=kind, frame=frame, proposed_args=dict(arguments),
                       visible_context=self.visible_context())
        elif result is not None and self.challenge is prior:
            result = {'status': 'release_not_executed',
                      'challenge_id': prior['challenge_id'],
                      'message': 'The release remains pending a new model response; it has not executed.'}
        elif result is None and prior is not None:
            self.audit('ase_release_confirmed', challenge_id=prior['challenge_id'],
                       release_kind=kind, frame=frame, visible_context=self.visible_context())
        return result

    def next_tool(self, name, arguments):
        active = self.challenge
        super().next_tool(name, arguments)
        if active is not None and name not in {'wait', 'allow_complete'}:
            self.audit('ase_post_boundary_tool', challenge_id=active['challenge_id'],
                       tool_name=name, model_turn=self.model_turn,
                       issued_at_model_turn=active['issued_at_model_turn'],
                       task_path=arguments.get('path') if name == 'file_read' else None,
                       command_sha256=digest(arguments.get('code')) if name == 'code_run' and
                       arguments.get('code') is not None else None)

    def abandon(self, disposition):
        active = self.challenge
        super().abandon(disposition)
        if active is not None:
            self.audit('ase_release_abandoned', challenge_id=active['challenge_id'],
                       disposition=disposition)

    def end_review(self, reason):
        active = self.challenge
        super().end_review(reason)
        if active is not None:
            self.audit('ase_review_ended_with_boundary_pending',
                       challenge_id=active['challenge_id'], disposition=reason)
