FROM znpt/roadmapbench-fyn-2.2.0-roadmap:latest AS go_source
FROM debian:bookworm-slim
COPY --from=go_source /usr/local/go /usr/local/go
ENV PATH=/usr/local/go/bin:$PATH GOPROXY=off GOSUMDB=off CGO_ENABLED=0
WORKDIR /app
